dataset_name: "cub2011"
backbone: "convnextv2_base.fcmae_ft_in22k_in1k"

training:
  num_epochs: 30
  #visualize: True

data:
  batch_size_train: 64
  batch_size_test: 64
  num_workers: 4

logger:
  wandb: true
