dataset_name: "cub2011"
backbone: "convnextv2_base.fcmae_ft_in22k_in1k"

training:
  num_epochs: 10
  visualize: True

data:
  batch_size_train: 512
  batch_size_test: 512
  num_workers: 4

logger:
  wandb: False
